name: Запуск тестов лабораторной работы

on:
  push:
    branches: [ "number_6" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-common-ci:
    uses: IlyaKorol-08/Kings/.github/workflows/c-ci.yml@main
    with:
      make-target: 'all'
      run-tests: true
    secrets: inherit
